import 'package:http/http.dart' as http;
import 'package:lvflutter/const.dart';
import 'package:dio/dio.dart';

class RemoteProfileService {
  var client = http.Client();
  var remoteURL = '$baseUrl/auth/admin/user/profile';

  Future<dynamic> get() async {
    final dio = Dio();
    final response = await dio.get(
      '$remoteURL',
      options: Options(
        headers: {
          'Authorization':
              'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhVmFsdWVzIjp7ImlkIjozMywiZmlyc3ROYW1lIjoiQjE5MTAzMTYiLCJsYXN0TmFtZSI6Ik5ndXllbiBUaGkgTmdvYyBUcmFtIiwiZW1haWwiOiJ0cmFtYjE5MTAzMTZAc3R1ZGVudC5jdHUuZWR1LnZuIiwicGFzc3dvcmQiOiIkMmIkMTAkQkNNMlA0UkhXbDhjbkVqMmtnTC40dWVOdURhM2lYMTJoVjYyQlF2RFoxanI3NDVnLkw3bFciLCJnZW5kZXIiOnRydWUsInBob25lIjoiMDEyMzQ1Njc4OSIsImFkZHJlc3MiOm51bGwsImdyb3VwX2lkIjoiMSIsImF2YXRhciI6Imh0dHBzOi8vcmVzLmNsb3VkaW5hcnkuY29tL2RtZXlyenpqcC9pbWFnZS91cGxvYWQvdjE2OTI0MjI2NDQvaG9tZS96ZGJlcWNidGV2OTBhbHRxbWE3aS5qcGciLCJiZ19pbWciOiJodHRwOi8vcmVzLmNsb3VkaW5hcnkuY29tL2RtZXlyenpqcC9pbWFnZS91cGxvYWQvdjE2ODMyMDY1MzAvaG9tZS9tcXpxM2I1ZnZzOGdrb3Nua2VyZC5qcGciLCJkZXNjcmlwdGlvbiI6IjxwPkLDoW5oIMO6PC9wPiIsImlkX2ZhY2Vib29rIjpudWxsLCJjb2luIjo1MDAwLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTAzIDEwOjIwOjAwIiwidXBkYXRlZEF0IjoiMjAyMy0wOC0xOSAxMjoyNDowNCIsImRlbGV0ZWRBdCI6bnVsbH0sIl9wcmV2aW91c0RhdGFWYWx1ZXMiOnsiaWQiOjMzLCJmaXJzdE5hbWUiOiJCMTkxMDMxNiIsImxhc3ROYW1lIjoiTmd1eWVuIFRoaSBOZ29jIFRyYW0iLCJlbWFpbCI6InRyYW1iMTkxMDMxNkBzdHVkZW50LmN0dS5lZHUudm4iLCJwYXNzd29yZCI6IiQyYiQxMCRCQ00yUDRSSFdsOGNuRWoya2dMLjR1ZU51RGEzaVgxMmhWNjJCUXZEWjFqcjc0NWcuTDdsVyIsImdlbmRlciI6dHJ1ZSwicGhvbmUiOiIwMTIzNDU2Nzg5IiwiYWRkcmVzcyI6bnVsbCwiZ3JvdXBfaWQiOiIxIiwiYXZhdGFyIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZG1leXJ6empwL2ltYWdlL3VwbG9hZC92MTY5MjQyMjY0NC9ob21lL3pkYmVxY2J0ZXY5MGFsdHFtYTdpLmpwZyIsImJnX2ltZyI6Imh0dHA6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZG1leXJ6empwL2ltYWdlL3VwbG9hZC92MTY4MzIwNjUzMC9ob21lL21xenEzYjVmdnM4Z2tvc25rZXJkLmpwZyIsImRlc2NyaXB0aW9uIjoiPHA-QsOhbmggw7o8L3A-IiwiaWRfZmFjZWJvb2siOm51bGwsImNvaW4iOjUwMDAsImNyZWF0ZWRBdCI6IjIwMjMtMDUtMDMgMTA6MjA6MDAiLCJ1cGRhdGVkQXQiOiIyMDIzLTA4LTE5IDEyOjI0OjA0IiwiZGVsZXRlZEF0IjpudWxsfSwidW5pcW5vIjoxLCJfY2hhbmdlZCI6e30sIl9vcHRpb25zIjp7ImlzTmV3UmVjb3JkIjpmYWxzZSwiX3NjaGVtYSI6bnVsbCwiX3NjaGVtYURlbGltaXRlciI6IiIsInJhdyI6dHJ1ZSwiYXR0cmlidXRlcyI6WyJpZCIsImZpcnN0TmFtZSIsImxhc3ROYW1lIiwiZW1haWwiLCJwYXNzd29yZCIsImdlbmRlciIsInBob25lIiwiYWRkcmVzcyIsImdyb3VwX2lkIiwiYXZhdGFyIiwiYmdfaW1nIiwiZGVzY3JpcHRpb24iLCJpZF9mYWNlYm9vayIsImNvaW4iLCJjcmVhdGVkQXQiLCJ1cGRhdGVkQXQiLCJkZWxldGVkQXQiXX0sImlzTmV3UmVjb3JkIjpmYWxzZSwiaWF0IjoxNjkzNDYzNzc3LCJleHAiOjE2OTM0NjczNzd9.BQ82tXET36umTZ2PX0x67U4sqpbrw0yzNvocEM6JAxo'
        },
      ),
    );
    print(response.data);

    // var response = await client.get(Uri.parse('$remoteURL'), headers: {
    //   'Content-Type': 'application/json',
    //   'Accept': 'application/json',
    //   'Authorization':
    //       'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhVmFsdWVzIjp7ImlkIjozMywiZmlyc3ROYW1lIjoiQjE5MTAzMTYiLCJsYXN0TmFtZSI6Ik5ndXllbiBUaGkgTmdvYyBUcmFtIiwiZW1haWwiOiJ0cmFtYjE5MTAzMTZAc3R1ZGVudC5jdHUuZWR1LnZuIiwicGFzc3dvcmQiOiIkMmIkMTAkQkNNMlA0UkhXbDhjbkVqMmtnTC40dWVOdURhM2lYMTJoVjYyQlF2RFoxanI3NDVnLkw3bFciLCJnZW5kZXIiOnRydWUsInBob25lIjoiMDEyMzQ1Njc4OSIsImFkZHJlc3MiOm51bGwsImdyb3VwX2lkIjoiMSIsImF2YXRhciI6Imh0dHBzOi8vcmVzLmNsb3VkaW5hcnkuY29tL2RtZXlyenpqcC9pbWFnZS91cGxvYWQvdjE2OTI0MjI2NDQvaG9tZS96ZGJlcWNidGV2OTBhbHRxbWE3aS5qcGciLCJiZ19pbWciOiJodHRwOi8vcmVzLmNsb3VkaW5hcnkuY29tL2RtZXlyenpqcC9pbWFnZS91cGxvYWQvdjE2ODMyMDY1MzAvaG9tZS9tcXpxM2I1ZnZzOGdrb3Nua2VyZC5qcGciLCJkZXNjcmlwdGlvbiI6IjxwPkLDoW5oIMO6PC9wPiIsImlkX2ZhY2Vib29rIjpudWxsLCJjb2luIjo1MDAwLCJjcmVhdGVkQXQiOiIyMDIzLTA1LTAzIDEwOjIwOjAwIiwidXBkYXRlZEF0IjoiMjAyMy0wOC0xOSAxMjoyNDowNCIsImRlbGV0ZWRBdCI6bnVsbH0sIl9wcmV2aW91c0RhdGFWYWx1ZXMiOnsiaWQiOjMzLCJmaXJzdE5hbWUiOiJCMTkxMDMxNiIsImxhc3ROYW1lIjoiTmd1eWVuIFRoaSBOZ29jIFRyYW0iLCJlbWFpbCI6InRyYW1iMTkxMDMxNkBzdHVkZW50LmN0dS5lZHUudm4iLCJwYXNzd29yZCI6IiQyYiQxMCRCQ00yUDRSSFdsOGNuRWoya2dMLjR1ZU51RGEzaVgxMmhWNjJCUXZEWjFqcjc0NWcuTDdsVyIsImdlbmRlciI6dHJ1ZSwicGhvbmUiOiIwMTIzNDU2Nzg5IiwiYWRkcmVzcyI6bnVsbCwiZ3JvdXBfaWQiOiIxIiwiYXZhdGFyIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZG1leXJ6empwL2ltYWdlL3VwbG9hZC92MTY5MjQyMjY0NC9ob21lL3pkYmVxY2J0ZXY5MGFsdHFtYTdpLmpwZyIsImJnX2ltZyI6Imh0dHA6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZG1leXJ6empwL2ltYWdlL3VwbG9hZC92MTY4MzIwNjUzMC9ob21lL21xenEzYjVmdnM4Z2tvc25rZXJkLmpwZyIsImRlc2NyaXB0aW9uIjoiPHA-QsOhbmggw7o8L3A-IiwiaWRfZmFjZWJvb2siOm51bGwsImNvaW4iOjUwMDAsImNyZWF0ZWRBdCI6IjIwMjMtMDUtMDMgMTA6MjA6MDAiLCJ1cGRhdGVkQXQiOiIyMDIzLTA4LTE5IDEyOjI0OjA0IiwiZGVsZXRlZEF0IjpudWxsfSwidW5pcW5vIjoxLCJfY2hhbmdlZCI6e30sIl9vcHRpb25zIjp7ImlzTmV3UmVjb3JkIjpmYWxzZSwiX3NjaGVtYSI6bnVsbCwiX3NjaGVtYURlbGltaXRlciI6IiIsInJhdyI6dHJ1ZSwiYXR0cmlidXRlcyI6WyJpZCIsImZpcnN0TmFtZSIsImxhc3ROYW1lIiwiZW1haWwiLCJwYXNzd29yZCIsImdlbmRlciIsInBob25lIiwiYWRkcmVzcyIsImdyb3VwX2lkIiwiYXZhdGFyIiwiYmdfaW1nIiwiZGVzY3JpcHRpb24iLCJpZF9mYWNlYm9vayIsImNvaW4iLCJjcmVhdGVkQXQiLCJ1cGRhdGVkQXQiLCJkZWxldGVkQXQiXX0sImlzTmV3UmVjb3JkIjpmYWxzZSwiaWF0IjoxNjkyODgxNzQ1LCJleHAiOjE2OTI4ODUzNDV9.S59eMPzuZvnv4J1M58XUObnz3iObG0UouDsdo0l55lI',
    // });
    return response.data;
  }
}
